spring.application.name=stage-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/stage_manager

spring.datasource.username=postgres

spring.datasource.password=Imane"2004

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080